### ISSUE TITLE
Can you create a Windows style title bar?

### ISSUE THREAD

**Issue by StunxFS** [B00merang-Project/Brilliance#2]
Good, I've tried the subject and it's great, it was what I was looking for. But my question is: Can you make the application icon appear in the title bar? Windows style? That would be much better for me.

**Comment by Elbullazul** [comment]
It may still be possible for MATE desktop. I know Cinnamon discontinued the window icon feature with metacity 3.

just to make shure, you want something like this:
![image](https://user-images.githubusercontent.com/15310985/72295376-6e461d00-3625-11ea-9e61-dd9ea66bd031.png)
(referring to the explorer icon)

**Comment by StunxFS** [comment]
Yes, yes, that was what I meant. By the way, I use Xfce.
Another thing, if it's not too much trouble, can you change the gray color of the theme for a darker one? I don't like the color it has.
That would be for the Ambiance Blackout Flat Red

The color could be this:
![imagen](https://user-images.githubusercontent.com/56417208/72303119-9abc6200-3642-11ea-8728-8924a2cd1ca3.png)

Thanks for answering :)

**Comment by Elbullazul** [comment]
I don't think Xfce has support for this feature. All the themes I've seen come with static assets and there is no scripting support for something like this

**Comment by Elbullazul** [comment]
can you put an example of the gray you're talking about?

**Comment by StunxFS** [comment]
> I don't think Xfce has support for this feature. All the themes I've seen come with static assets and there is no scripting support for something like this


![imagen](https://user-images.githubusercontent.com/56417208/72336136-8ace6d80-3696-11ea-85cc-47f1323158bb.png)
This is the title bar that I have, and it has the application icon open. But there is no problem with it.

> can you put an example of the gray you're talking about?


![imagen](https://user-images.githubusercontent.com/56417208/72336236-bf422980-3696-11ea-8e87-b6ebe3862678.png)
To that gray color that is first I mean.

Thanks for answering!

**Comment by Elbullazul** [comment]
do you have firefox's native titlebar enabled? 

1. Open firefox's main menu
2. Select ‘customise’
3. Is the ‘title bar’ box checked?

about the color, the idea was to port the look and feel of OG ambiance blackout.
as this images show,
![img](https://4.bp.blogspot.com/-GrMD6_lgmto/VTlk0KffQ_I/AAAAAAAAFC0/PJ--gREy4ag/s1600/BlackoutMainBanner2015.png)

![img](https://github.com/B00merang-Project/gallery/raw/master/Brilliance%20Dark%20(1).png)

we follow the color palette RAVEfinity created. (titlebar should be darker though)

However, if you want a darker remake I'm open to rework [B00merang Brome](https://github.com/B00merang-Project/B00merang-Brome) to closer match what you want. Here's what it looks like at the moment:
![img](https://github.com/B00merang-Project/gallery/raw/master/B00merang%20Brome%20(1).png)

I think it look close enough and only minor color changes should be needed.  What do you think?

**Comment by StunxFS** [comment]
First of all, thanks for the native Firefox bar, I finally was able to hide it, and that I searched a lot on the internet, and it was a simple popcorn in the Personalization section that I had not seen xD.
Second, on the theme, I understand that you want to follow the use of a created palette.
About B00merang Brome, i think it's a good idea :).

Won't you have Discord?

Thanks for answering!

**Comment by StunxFS** [comment]
Well, it's been a long time after this ... I better close the subject

**Comment by Elbullazul** [comment]
Pretty sure the feature doesn't work on xfce. Anyways, I'm still going to do the recolor when I find myself some time to do it

**Comment by StunxFS** [comment]
Yes it works in XFCE (we talk about the icons in the window, right?), There is an option that allows you to put it in the titlebar easily.
It is this option: `show app_icon`, if it is true it shows the icon.

![imagen](https://user-images.githubusercontent.com/56417208/84388881-4b636900-abc3-11ea-8bf4-4e56ffe63461.png)
From: https://wiki.xfce.org/howto/xfwm4_theme

**Comment by Elbullazul** [comment]
interesting. Will have a look when possible

**Comment by StunxFS** [comment]
okey :+1:

**Comment by Elbullazul** [comment]
finally found some time to work on this. The recolour is coming this week, will try the Xfce once that is complete

**Comment by StunxFS** [comment]
Great! I will be careful :wink:

**Comment by Elbullazul** [comment]
doesn't seem like it works correctly anymore:

![Xubuntu 20 04 beta-2020-10-04-19-02-18](https://user-images.githubusercontent.com/15310985/95029144-24e6a380-0674-11eb-9686-a0156bc353be.png)

sorry
